#!/usr/bin/env ruby

# Create symlinks from files -> home directory
#
# for example:
#
# ./zshrc -> ~/.zshrc

root = File.expand_path(File.dirname(__FILE__))
dotfiles_path = File.join(root, 'config')

files = `ls #{dotfiles_path}`.split - ['.', '..']

files.each do |filename|
  if File.directory?("#{dotfiles_path}/#{filename}")
    puts "directory #{filename} to ~/.config/#{filename}"
    system("ln -sf '#{dotfiles_path}/#{filename}' ~/.config/#{filename}")
  else
    puts "Linking file #{filename} to ~/.#{filename}"
    system("ln -sf '#{dotfiles_path}/#{filename}' ~/.#{filename}")
  end
end
