set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Plug and initialize
call plug#begin('~/.vim/plugged')

" General
Plug 'vim-airline/vim-airline'
Plug 'ervandew/supertab'
Plug 'mileszs/ack.vim'
Plug 'godlygeek/tabular'
Plug 'tpope/vim-projectionist'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'
Plug 'thisivan/vim-bufexplorer'
Plug 'gregsexton/MatchTag'
Plug 'kien/ctrlp.vim'
Plug 'bogado/file-line'
Plug 'bkad/CamelCaseMotion'
Plug 'mattn/emmet-vim'

" Appearance
Plug 'flazz/vim-colorschemes'
Plug 'drewtempelmeyer/palenight.vim'

" Git
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'

" Language support
Plug 'plasticboy/vim-markdown'
Plug 'pangloss/vim-javascript'
Plug 'elixir-lang/vim-elixir'
Plug 'rust-lang/rust.vim'
Plug 'TovarishFin/vim-solidity'
Plug 'hashivim/vim-terraform'

" Tests
Plug 'janko/vim-test'
Plug 'renderedtext/vim-elixir-alternative-files'

" All of your Plugins must be added before the following line
call plug#end() " required

filetype plugin indent on    " required
filetype plugin on

source ~/.vim/mappings.vim
source ~/.vim/config.vim
source ~/.vim/plugins_config.vim
