set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" General
Plugin 'vim-airline/vim-airline'
Plugin 'ervandew/supertab'
Plugin 'mileszs/ack.vim'
Plugin 'godlygeek/tabular'
Plugin 'tpope/vim-projectionist'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-commentary'
Plugin 'thisivan/vim-bufexplorer'
Plugin 'gregsexton/MatchTag'
Plugin 'kien/ctrlp.vim'
Plugin 'bogado/file-line'
Plugin 'bkad/CamelCaseMotion'
Plugin 'mattn/emmet-vim'

" Appearance
Plugin 'flazz/vim-colorschemes'
Plugin 'drewtempelmeyer/palenight.vim'

" Git
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'

" Language support
Plugin 'plasticboy/vim-markdown'
Plugin 'pangloss/vim-javascript'
Plugin 'elixir-lang/vim-elixir'
Plugin 'rust-lang/rust.vim'
Plugin 'TovarishFin/vim-solidity'
Plugin 'hashivim/vim-terraform'

" Tests
Plugin 'janko/vim-test'
Plugin 'renderedtext/vim-elixir-alternative-files'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
filetype plugin on

source ~/.vim/mappings.vim
source ~/.vim/config.vim
source ~/.vim/plugins_config.vim
