plugins=(git)

export EDITOR="vim"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

if [ "$TMUX" = "" ]; then tmux; fi

HISTSIZE=5000               # How many lines of history to keep in memory
HISTFILE=~/.zsh_history     # Where to save history to disk
SAVEHIST=5000               # Number of history entries to save to disk
HISTDUP=erase               # Erase duplicates in the history file
ZSH_THEME="spaceship"

setopt appendhistory     # Append history to the history file (no overwriting)
setopt sharehistory      # Share history across terminals
setopt incappendhistory  # Immediately append to the history file, not just when a term is killed
setopt autocd            # Change directories without cd
setopt rmstarsilent

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^ ' autosuggest-accept # CTRL + SPACE
bindkey '^^M' autosuggest-execute # CTRL + ENTER
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=243'

if [ -d ~/.kerl ]; then
  source ~/.kerl/installs/18.3/activate
  test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"
  kiex use 1.2.6
fi

if [ -d $HOME/bin ]; then
  export PATH=$PATH:$HOME/bin
fi

if [ -d $HOME/.gem.ruby/2.3.0 ]; then
  export PATH=$PATH:$HOME/.gem/ruby/2.3.0/bin
fi

if [ -d $HOME/go-code ]; then
  export GOPATH=$HOME/go-code
  export PATH=$HOME/go-code/bin:$PATH
fi

if [ -d $HOME/.nvm ]; then
  export NVM_DIR=$HOME/.nvm
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
fi

if [ -d $HOME/anaconda3/bin ]; then
  export PATH=$PATH:$HOME/anaconda3/bin
fi

# virtualenvwrapper
export VIRTUALENVWRAPPER_PYTHON=$HOME/anaconda3/bin/python
export WORKON_HOME=$HOME/Envs
source $HOME/anaconda3/bin/virtualenvwrapper.sh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH=$PATH:$HOME/.rvm/bin

eval `ssh-agent`
ssh-add ~/.ssh/id_rsa

SPACESHIP_PROMPT_ORDER=(
  time
  user
  host
  dir
  git
  docker
  kubectl
  ruby
  elixir
  julia
  venv
  pyenv
  jobs
  line_sep
  char
)

export SPACESHIP_JOBS_COLOR="yellow"

export ZSH=$HOME/.oh-my-zsh
source ~/.aliases
source $ZSH/oh-my-zsh.sh
