if [ "$TMUX" = "" ]; then tmux; fi
export EDITOR="vim"

HISTSIZE=5000               # How many lines of history to keep in memory
HISTFILE=~/.zsh_history     # Where to save history to disk
SAVEHIST=5000               # Number of history entries to save to disk
HISTDUP=erase               # Erase duplicates in the history file

setopt appendhistory     # Append history to the history file (no overwriting)
setopt sharehistory      # Share history across terminals
setopt incappendhistory  # Immediately append to the history file, not just when a term is killed
setopt autocd            # Change directories without cd

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.prompt
source ~/.aliases

# Bindings for auto completion [CTRL + SPACE]
bindkey '^ ' autosuggest-accept
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'

if [ -d ~/.kerl ]; then
  source ~/.kerl/installs/18.3/activate
  test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"
  kiex use 1.2.6
fi

if [ -d $HOME/bin ]; then
  export PATH=$PATH:$HOME/bin
fi

if [ -d $HOME/.gem.ruby/2.3.0 ]; then
  export PATH=$PATH:$HOME/.gem/ruby/2.3.0/bin
fi

if [ -d $HOME/go-code ]; then
  export GOPATH=$HOME/go-code
  export PATH=$HOME/go-code/bin:$PATH
fi

export NVM_DIR="/home/vonum/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="/home/vonum/anaconda2/bin:$PATH"
export PATH="/home/vonum/anaconda3/bin:$PATH"

# virtualenvwrapper
export WORKON_HOME=~/Envs
source ~/anaconda3/bin/virtualenvwrapper.sh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

alias vstart="cd ~/dev-box && vagrant up"
alias vssh="cd ~/dev-box && vagrant ssh"
alias vstop="cd ~/dev-box && vagrant halt"

alias vu="cd ~/dev-box && vagrant up && vagrant ssh"

eval `ssh-agent`
ssh-add ~/.ssh/id_rsa
